-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 13, 2024 at 09:16 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `alumnitracer`
--

-- --------------------------------------------------------

--
-- Table structure for table `alumni_information`
--

CREATE TABLE `alumni_information` (
  `id` int(11) NOT NULL,
  `alumni_name` varchar(255) DEFAULT NULL,
  `permanent_address` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `contact_number` varchar(20) DEFAULT NULL,
  `mobile_number` varchar(20) DEFAULT NULL,
  `civil_status` varchar(50) DEFAULT NULL,
  `sex` varchar(10) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `course` varchar(255) DEFAULT NULL,
  `campus` varchar(255) DEFAULT NULL,
  `location_of_residence` varchar(255) DEFAULT NULL,
  `degree_specialization` varchar(255) DEFAULT NULL,
  `college_or_university` varchar(255) DEFAULT NULL,
  `year_graduated` year(4) DEFAULT NULL,
  `honors_or_awards` varchar(255) DEFAULT NULL,
  `name_of_examination` varchar(255) DEFAULT NULL,
  `date_taken` date DEFAULT NULL,
  `rating` decimal(5,2) DEFAULT NULL,
  `education_level` varchar(255) DEFAULT NULL,
  `reasons_for_pursuing_degrees` varchar(255) DEFAULT NULL,
  `title_of_training` varchar(255) DEFAULT NULL,
  `duration_and_credits` varchar(255) DEFAULT NULL,
  `name_of_training` varchar(255) DEFAULT NULL,
  `pursue_advance` varchar(255) DEFAULT NULL,
  `employment_status` varchar(255) DEFAULT NULL,
  `not_employed_reasons` varchar(255) DEFAULT NULL,
  `present_employment_status` varchar(255) DEFAULT NULL,
  `self_employed_skills` varchar(255) DEFAULT NULL,
  `present_occupation` varchar(255) DEFAULT NULL,
  `business_line` varchar(255) DEFAULT NULL,
  `place_of_work` varchar(255) DEFAULT NULL,
  `first_job_after_college` varchar(255) DEFAULT NULL,
  `reasons_staying` varchar(255) DEFAULT NULL,
  `first_job_related` varchar(255) DEFAULT NULL,
  `reasons_accepting` varchar(255) DEFAULT NULL,
  `reasons_changing` varchar(255) DEFAULT NULL,
  `duration_first_job` varchar(255) DEFAULT NULL,
  `find_first_job` varchar(255) DEFAULT NULL,
  `time_to_land_first_job` varchar(255) DEFAULT NULL,
  `job_level_first_job` varchar(255) DEFAULT NULL,
  `job_level_current_job` varchar(255) DEFAULT NULL,
  `initial_gross_monthly_earning` varchar(255) DEFAULT NULL,
  `curriculum_relevance` varchar(255) DEFAULT NULL,
  `useful_competencies` varchar(255) DEFAULT NULL,
  `curriculum_suggestions` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `alumni_information`
--

INSERT INTO `alumni_information` (`id`, `alumni_name`, `permanent_address`, `email`, `contact_number`, `mobile_number`, `civil_status`, `sex`, `birthday`, `course`, `campus`, `location_of_residence`, `degree_specialization`, `college_or_university`, `year_graduated`, `honors_or_awards`, `name_of_examination`, `date_taken`, `rating`, `education_level`, `reasons_for_pursuing_degrees`, `title_of_training`, `duration_and_credits`, `name_of_training`, `pursue_advance`, `employment_status`, `not_employed_reasons`, `present_employment_status`, `self_employed_skills`, `present_occupation`, `business_line`, `place_of_work`, `first_job_after_college`, `reasons_staying`, `first_job_related`, `reasons_accepting`, `reasons_changing`, `duration_first_job`, `find_first_job`, `time_to_land_first_job`, `job_level_first_job`, `job_level_current_job`, `initial_gross_monthly_earning`, `curriculum_relevance`, `useful_competencies`, `curriculum_suggestions`) VALUES
(1, 'John Doe', '123 Main St', 'john.doe@example.com', '1234567890', '0987654321', 'Single', 'Male', '1990-01-01', 'Bachelor of Science in Computer Science', 'Main Campus', 'City', 'Software Engineering', 'Cavite State University', '2015', 'Cum Laude', 'Civil Service Examination', '2016-01-01', 90.00, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Strong passion for the profession', 'Software Development Training', '3 months, 12 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Software Developer', 'Information Technology', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Response to an advertisement', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Communication skills, Problem-solving skills', 'Add more practical exercises and projects'),
(2, 'Jane Doe', '456 Elm St', 'jane.doe@example.com', '9876543210', '1234567890', 'Married', 'Female', '1992-01-01', 'Bachelor of Science in Business Administration', 'Cavite City Campus', 'Municipality', 'Marketing', 'Cavite State University', '2018', 'Magna Cum Laude', 'Civil Service Examination', '2019-01-01', 95.00, 'Undergraduate', 'Good grades in high school, Influence of parents or relatives', 'Marketing Training', '2 months, 8 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Marketing Manager', 'Wholesale and Retail Trade', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Recommended by someone', '1 to 6 months', 'Managerial or Executive', 'Managerial or Executive', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Communication skills, Human Relations skills', 'Include more case studies and real-world applications'),
(3, 'Michael Smith', '789 Oak St', 'michael.smith@example.com', '4567891230', '3216549870', 'Single', 'Male', '1991-02-01', 'Bachelor of Science in Agriculture', 'Bacoor Campus', 'City', 'Agronomy', 'Cavite State University', '2016', NULL, NULL, NULL, NULL, 'Undergraduate', 'Strong passion for the profession, Prospect for immediate employment', 'Agriculture Training', '4 months, 10 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Agricultural Technician', 'Agriculture, Hunting and Forestry', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '2 years to less than 3 years', 'Job Fair or Public Employment Service Office (PESO)', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P5,000.00 to less than P10,000.00', 'Relevant', 'Entrepreneurial skills, Problem-solving skills', 'More hands-on training and fieldwork opportunities'),
(4, 'Emily Johnson', '321 Pine St', 'emily.johnson@example.com', '3219876540', '6543217890', 'Single Parent', 'Female', '1989-03-01', 'Bachelor of Science in Hospitality Management', 'Gen. Mariano Alvarez Campus', 'Municipality', 'Culinary Arts', 'Cavite State University', '2017', 'Cum Laude', 'Civil Service Examination', '2018-01-01', 88.00, 'Undergraduate', 'Good grades in high school, Inspired by a role model', 'Culinary Training', '3 months, 12 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Chef', 'Hotels and Restaurants', 'Local', 'Yes', 'Salaries and benefits, Related to special skill', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'As walk-in applicant', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Communication skills, Critical Thinking skills', 'Incorporate more practical cooking sessions'),
(5, 'David Brown', '654 Maple St', 'david.brown@example.com', '7891234560', '9876543210', 'Married', 'Male', '1988-04-01', 'Bachelor of Science in Civil Engineering', 'Indang Campus', 'City', 'Structural Engineering', 'Cavite State University', '2014', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Status or prestige of the profession', 'Engineering Training', '6 months, 15 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Civil Engineer', 'Construction', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '2 years to less than 3 years', 'Recommended by someone', '1 to 6 months', 'Managerial or Executive', 'Managerial or Executive', 'P20,000.00 to less than P25,000.00', 'Relevant', 'Problem-solving skills, Information Technology skills', 'Enhance project management components'),
(6, 'Sophia Wilson', '987 Birch St', 'sophia.wilson@example.com', '6543219870', '3214567890', 'Widow', 'Female', '1990-05-01', 'Bachelor of Science in Psychology', 'Tanza Campus', 'Municipality', 'Clinical Psychology', 'Cavite State University', '2019', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Strong passion for the profession', 'Psychology Training', '5 months, 10 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Psychologist', 'Health and Social Work', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Information from friends', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Communication skills, Human Relations skills', 'Include more internship opportunities'),
(7, 'James Taylor', '135 Cedar St', 'james.taylor@example.com', '3216549870', '6547893210', 'Single', 'Male', '1993-06-01', 'Bachelor of Science in Electrical Engineering', 'Naic Campus', 'City', 'Power Systems', 'Cavite State University', '2015', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Prospect for attractive compensation', 'Electrical Training', '3 months, 12 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Electrical Engineer', 'Electricity, Gas and Water Supply', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Job Fair or Public Employment Service Office (PESO)', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P20,000.00 to less than P25,000.00', 'Relevant', 'Information Technology skills, Problem-solving skills', 'Add more lab sessions and practical work'),
(8, 'Isabella Martinez', '246 Spruce St', 'isabella.martinez@example.com', '7896541230', '3219876540', 'Married', 'Female', '1994-07-01', 'Bachelor of Science in Food Technology', 'Silang Campus', 'Municipality', 'Food Safety', 'Cavite State University', '2018', 'Cum Laude', 'Civil Service Examination', '2019-01-01', 92.00, 'Undergraduate', 'Good grades in high school, Availability of course offering in chosen institution', 'Food Safety Training', '2 months, 8 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Food Technologist', 'Manufacturing', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Response to an advertisement', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Communication skills, Critical Thinking skills', 'Incorporate more industry visits'),
(9, 'Liam Anderson', '369 Fir St', 'liam.anderson@example.com', '4561237890', '7893216540', 'Single', 'Male', '1995-08-01', 'Bachelor of Science in Mechanical Engineering', 'Cavite City Campus', 'City', 'Thermal Systems', 'Cavite State University', '2017', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Strong passion for the profession', 'Mechanical Training', '4 months, 10 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Mechanical Engineer', 'Manufacturing', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '2 years to less than 3 years', 'As walk-in applicant', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Problem-solving skills, Information Technology skills', 'Enhance design projects in the curriculum'),
(10, 'Mia Thomas', '852 Willow St', 'mia.thomas@example.com', '3214567890', '6541237890', 'Single', 'Female', '1996-09-01', 'Bachelor of Science in Environmental Science', 'Indang Campus', 'Municipality', 'Environmental Management', 'Cavite State University', '2019', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Inspired by a role model', 'Environmental Training', '3 months, 12 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Environmental Consultant', 'Other Community, Social and Personal Service Activities', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Information from friends', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Communication skills, Critical Thinking skills', 'Include more fieldwork opportunities'),
(11, 'Noah Jackson', '963 Chestnut St', 'noah.jackson@example.com', '7894561230', '3216549870', 'Single', 'Male', '1997-10-01', 'Bachelor of Science in Accountancy', 'Cavite City Campus', 'City', 'Financial Accounting', 'Cavite State University', '2020', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Status or prestige of the profession', 'Accounting Training', '2 months, 8 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Accountant', 'Financial Intermediation', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Response to an advertisement', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Communication skills, Problem-solving skills', 'Add more practical accounting exercises'),
(12, 'Ava White', '147 Maple St', 'ava.white@example.com', '6547893210', '9876543210', 'Married', 'Female', '1998-11-01', 'Bachelor of Science in Social Work', 'Bacoor Campus', 'Municipality', 'Community Development', 'Cavite State University', '2021', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Strong passion for the profession', 'Social Work Training', '3 months, 10 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Social Worker', 'Health and Social Work', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Job Fair or Public Employment Service Office (PESO)', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Communication skills, Human Relations skills', 'Include more community engagement projects'),
(13, 'Elijah Harris', '258 Oak St', 'elijah.harris@example.com', '3219876540', '6543217890', 'Single', 'Male', '1999-12-01', 'Bachelor of Science in Criminology', 'Gen. Mariano Alvarez Campus', 'City', 'Forensic Science', 'Cavite State University', '2022', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Inspired by a role model', 'Criminology Training', '4 months, 12 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Forensic Analyst', 'Public Administration and Defense', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Recommended by someone', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Problem-solving skills, Critical Thinking skills', 'Enhance practical training in forensic techniques'),
(14, 'Charlotte Lee', '369 Pine St', 'charlotte.lee@example.com', '6543219870', '3216549870', 'Single', 'Female', '2000-01-01', 'Bachelor of Science in Animal Science', 'Tanza Campus', 'Municipality', 'Animal Nutrition', 'Cavite State University', '2023', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Strong passion for the profession', 'Animal Science Training', '5 months, 10 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Animal Scientist', 'Agriculture, Hunting and Forestry', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'As walk-in applicant', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Communication skills, Problem-solving skills', 'Include more field studies in animal care'),
(15, 'Amelia King', '147 Cedar St', 'amelia.king@example.com', '7896543210', '3214569870', 'Married', 'Female', '2001-02-01', 'Bachelor of Science in Forestry', 'Cavite City Campus', 'City', 'Forest Management', 'Cavite State University', '2020', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Inspired by a role model', 'Forestry Training', '3 months, 12 credits', 'Cavite State University', 'For promotion', 'Yes', NULL, 'Regular or Permanent', NULL, 'Forester', 'Agriculture, Hunting and Forestry', 'Local', 'Yes', 'Salaries and benefits, Career challenge', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Job Fair or Public Employment Service Office (PESO)', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Communication skills, Critical Thinking skills', 'Include more environmental conservation projects'),
(16, 'Oliver Wright', '258 Birch St', 'oliver.wright@example.com', '3216547890', '6543219870', 'Single', 'Male', '2002-03-01', 'Bachelor of Science in Information Technology', 'Silang Campus', 'Municipality', 'Web Development', 'Cavite State University', '2021', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Strong passion for the profession', 'Web DevelopmentTraining', '4 months, 10 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Web Developer', 'Information Technology', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Response to an advertisement', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Information Technology skills, Problem-solving skills', 'Incorporate more coding projects in the curriculum'),
(17, 'Evelyn Scott', '369 Maple St', 'evelyn.scott@example.com', '6549873210', '3216547890', 'Widow', 'Female', '2003-04-01', 'Bachelor of Science in Nursing', 'Cavite City Campus', 'City', 'Clinical Nursing', 'Cavite State University', '2022', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Strong passion for the profession', 'Nursing Training', '5 months, 12 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Registered Nurse', 'Health and Social Work', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Job Fair or Public Employment Service Office (PESO)', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Communication skills, Human Relations skills', 'Include more clinical practice opportunities'),
(18, 'Henry Young', '147 Cedar St', 'henry.young@example.com', '7893216540', '6549873210', 'Single', 'Male', '2004-05-01', 'Bachelor of Science in Environmental Engineering', 'Bacoor Campus', 'Municipality', 'Sustainable Development', 'Cavite State University', '2023', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Inspired by a role model', 'Environmental Engineering Training', '4 months, 10 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Environmental Engineer', 'Environmental Management', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Information from friends', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P10,000.00 to less than P15,000.00', 'Relevant', 'Problem-solving skills, Critical Thinking skills', 'Include more projects on sustainable practices'),
(19, 'Grace Hall', '258 Birch St', 'grace.hall@example.com', '3216549870', '7896543210', 'Married', 'Female', '2005-06-01', 'Bachelor of Science in Marketing', 'Silang Campus', 'City', 'Digital Marketing', 'Cavite State University', '2021', NULL, NULL, NULL, NULL, 'Undergraduate', 'High grades in the course or subject area(s) related to the course, Strong passion for the profession', 'Marketing Training', '3 months, 8 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Digital Marketing Specialist', 'Wholesale and Retail Trade', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Response to an advertisement', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P15,000.00 to less than P20,000.00', 'Relevant', 'Communication skills, Information Technology skills', 'Incorporate more digital tools in the curriculum'),
(20, 'Lucas Green', '369 Oak St', 'lucas.green@example.com', '6543217890', '3219876540', 'Single', 'Male', '2006-07-01', 'Bachelor of Science in Information Systems', 'Cavite City Campus', 'Municipality', 'Systems Analysis', 'Cavite State University', '2022', NULL, NULL, NULL, NULL, 'Undergraduate', 'Good grades in high school, Inspired by a role model', 'Information Systems Training', '4 months, 10 credits', 'Cavite State University', 'For professional development', 'Yes', NULL, 'Regular or Permanent', NULL, 'Systems Analyst', 'Information Technology', 'Local', 'Yes', 'Salaries and benefits, Related to course or program of study', 'Yes', 'Salaries & benefits, Career challenge', 'Salaries & benefits, Career challenge', '1 year to less than 2 years', 'Job Fair or Public Employment Service Office (PESO)', '1 to 6 months', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P20,000.00 to less than P25,000.00', 'Relevant', 'Problem-solving skills, Critical Thinking skills', 'Include more case studies in systems analysis'),
(21, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'Prospect of career advancement, Affordable for the family, Prospect of attractive compensation', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(22, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'Affordable for the family', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(23, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'Strong passion for the profession, Prospect of career advancement', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(24, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'Prospect of career advancement, Affordable for the family', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(25, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'Influence of parents or relatives, Prospect for immediate employment', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(26, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'High grades in the course or subject area(s) related to the course, Good grades in high school, Influence of parents or relatives', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(27, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, 'High grades in the course or subject area(s) related to the course, Good grades in high school, Strong passion for the profession', '', '', '', NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', ''),
(28, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, '', '', '', '', NULL, 'No', 'Advance or further study, Lack of work experience, other_not_employed_reasons', NULL, '', '', NULL, NULL, 'Yes', 'Salaries and benefits, Peer influence', 'Yes', 'Career challenge, Related to special skills', 'Salaries & benefits', '2 years to less than 3 years', 'Recommended by someone', '1 year to less than 2 years', 'Professional, Technical or Supervisory', 'Professional, Technical or Supervisory', 'P20,000.00 to less than P25,000.00', 'Yes', 'Information Technology skills, Problem-solving skills', 'Magnakaw'),
(29, '', '', '', '', '', NULL, NULL, '0000-00-00', NULL, NULL, NULL, '', '', '0000', '', '', '0000-00-00', 0.00, NULL, '', '', '', '', NULL, 'Yes', 'Advance or further study, No job opportunity', 'Self-employed', 'asdadsasd', '', NULL, NULL, NULL, '', NULL, '', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `alumni_information`
--
ALTER TABLE `alumni_information`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `alumni_information`
--
ALTER TABLE `alumni_information`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
